#ifndef CDFT_4_LOAD
#define CDFT_4_LOAD CDFT_LOAD
#endif

#ifndef CDFT_4_STORE
#define CDFT_4_STORE CDFT_STORE
#endif

#ifndef CDFT_4_INPUT_INDEX
#define CDFT_4_INPUT_INDEX(i) (i)
#endif

#ifndef CDFT_4_OUTPUT_INDEX
#define CDFT_4_OUTPUT_INDEX(i) (i)
#endif

{
  CV_VECTOR z0, z1, z2, z3;
  CDFT_4_LOAD(CDFT_4_INPUT_INDEX(0), &z0);
  CDFT_4_LOAD(CDFT_4_INPUT_INDEX(2), &z1);
  CV_DFT2(&z0, &z1);
  CDFT_4_LOAD(CDFT_4_INPUT_INDEX(1), &z2);
  CDFT_4_LOAD(CDFT_4_INPUT_INDEX(3), &z3);
  CV_DFT2(&z2, &z3);
  CV_DFT2(&z0, &z2);
  CDFT_4_STORE(CDFT_4_OUTPUT_INDEX(0), z0);
  CDFT_4_STORE(CDFT_4_OUTPUT_INDEX(2), z2);
  CV_C_MULI_DFT2(&z1, &z3);
  CDFT_4_STORE(CDFT_4_OUTPUT_INDEX(1), z1);
  CDFT_4_STORE(CDFT_4_OUTPUT_INDEX(3), z3);
}

#undef CDFT_4_LOAD
#undef CDFT_4_STORE
#undef CDFT_4_INPUT_INDEX
#undef CDFT_4_OUTPUT_INDEX
